blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/trueagi-io/FabricPC/blob/main/CONTRIBUTING.md#questions
    about: Please ask questions in discussions or consult CONTRIBUTING.md.
